#!/bin/bash
python ../../data/create_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean -k 3
python run_model_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean.fold.0 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.1 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.2 -s 6233 -c entropy -m 6 -i 250 -l 50 -x 150 -j 10 >> ../../data/data_no_master/results.csv
python ../../data/create_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean -k 3
python run_model_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean.fold.0 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.1 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.2 -s 6233 -c entropy -m 6 -i 250 -l 50 -x 150 -j 10 >> ../../data/data_no_master/results.csv
python ../../data/create_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean -k 3
python run_model_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean.fold.0 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.1 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.2 -s 6233 -c entropy -m 6 -i 250 -l 50 -x 150 -j 10 >> ../../data/data_no_master/results.csv
python ../../data/create_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean -k 3
python run_model_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean.fold.0 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.1 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.2 -s 6233 -c entropy -m 6 -i 250 -l 50 -x 150 -j 10 >> ../../data/data_no_master/results.csv
python ../../data/create_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean -k 3
python run_model_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean.fold.0 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.1 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.2 -s 6233 -c entropy -m 6 -i 250 -l 50 -x 150 -j 10 >> ../../data/data_no_master/results.csv
python ../../data/create_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean -k 3
python run_model_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean.fold.0 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.1 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.2 -s 6233 -c entropy -m 6 -i 250 -l 50 -x 150 -j 10 >> ../../data/data_no_master/results.csv
python ../../data/create_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean -k 3
python run_model_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean.fold.0 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.1 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.2 -s 6233 -c entropy -m 6 -i 250 -l 50 -x 150 -j 10 >> ../../data/data_no_master/results.csv
python ../../data/create_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean -k 3
python run_model_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean.fold.0 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.1 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.2 -s 6233 -c entropy -m 6 -i 250 -l 50 -x 150 -j 10 >> ../../data/data_no_master/results.csv
python ../../data/create_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean -k 3
python run_model_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean.fold.0 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.1 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.2 -s 6233 -c entropy -m 6 -i 250 -l 50 -x 150 -j 10 >> ../../data/data_no_master/results.csv
python ../../data/create_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean -k 3
python run_model_folds.py -f ../../data/data_no_master/data_no_master.csv.removed.clean.fold.0 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.1 ../../data/data_no_master/data_no_master.csv.removed.clean.fold.2 -s 6233 -c entropy -m 6 -i 250 -l 50 -x 150 -j 10 >> ../../data/data_no_master/results.csv
