#!/bin/bash
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 3455 -c 100000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 6634 -c 99000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 2055 -c 98000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 4501 -c 97000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 6965 -c 96000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 9521 -c 95000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 9679 -c 94000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 8362 -c 93000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 8022 -c 92000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 9077 -c 91000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 3324 -c 90000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 8878 -c 89000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 1882 -c 88000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 4973 -c 87000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 9479 -c 86000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 8670 -c 85000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 761 -c 84000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 768 -c 83000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 6203 -c 82000 >> results/data_and_custom_no_rem_tendency/lr_2.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 5467 -c 81000 >> results/data_and_custom_no_rem_tendency/lr_2.txt

