#!/bin/bash
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 6352 -c 80000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 8085 -c 79000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 9968 -c 78000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 6965 -c 77000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 2553 -c 76000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 874 -c 75000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 816 -c 74000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 686 -c 73000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 172 -c 72000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 4537 -c 71000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 2004 -c 70000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 5844 -c 69000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 5804 -c 68000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 9410 -c 67000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 4511 -c 66000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 6975 -c 65000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 6183 -c 64000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 1597 -c 63000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 6294 -c 62000 >> results/data_and_custom_no_rem_tendency/lr_3.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 380 -c 61000 >> results/data_and_custom_no_rem_tendency/lr_3.txt

