#!/bin/bash
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 933 -c 19000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 5968 -c 18000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 1966 -c 17000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 9396 -c 16000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 2944 -c 15000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 4671 -c 14000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 1200 -c 13000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 3000 -c 12000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 3285 -c 11000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 4158 -c 10000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 7754 -c 9000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 9572 -c 8000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 1980 -c 7000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 8510 -c 6000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 1928 -c 5000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 7829 -c 4000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 8692 -c 3000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 1394 -c 2000 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 6229 -c 900 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 1937 -c 800 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 3690 -c 700 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 6322 -c 600 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 9040 -c 500 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 3589 -c 400 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 5032 -c 300 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 5536 -c 200 >> results/data_and_custom_no_rem_tendency/lr_1.txt
python run_model_folds_lr.py -f ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.0 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.1 ../../data/data_and_custom_no_rem_tendency/data_and_custom_tendency.csv.clean.fold.2 -s 4350 -c 100
